### ISSUE TITLE
Analysis of the SHA512 algorithm

### ISSUE THREAD

**Issue by software-engineering-labs6412** [software-engineering-labs6412/private-channel#1]
Изучить алгоритм SHA512:
1) Основные принципы;
2) Как это должно работать (в общем плане хотя бы);
3) Посмотреть, как это можно реализовать на Java.

**Comment by Denishka** [comment]
1. Основные принципы
Хеш- алгоритм SHA-512 является алгоритмом из семейства SHA-2.предназначен, для создания дайджестов сообщений произвольной длинны. Алгоритм состоит из двух этапов. 
 На первом этапе происходит предварительная обработка, на втором, в
свою очередь, вычисление хеша. 
 Во время предварительной обработки
входящее сообщение дополняется, разбивается на битные блоки, после чего устанавливаются инициализирующие значения. Размер входного сообщения, для алгоритма SHA-512 должен быть меньше чем 2^128. Размер блока после разбиения составляет 1024 бита, а размер дайджеста 512 бит.

2. Как это должно работать
Для начала создается переменную, которая будет хранить дайджест, конкретно для алгоритма SHA-512. После чего передаем строку с входными данными, где хранятся конкатенация пароля и логина, для преобразований с помощью алгоритма, затем получаем искомый дайджест для входного
сообщения.

3. Реализация
Для вычисления значения криптографического хэширования в Java используется класс MessageDigest в пакете java.security . В пакет входит в том числе и SHA-512

```
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
  
public class GFG {
    public static String encryptThisString(String input)
    {
        try {
            // getInstance() method is called with algorithm SHA-512
            MessageDigest md = MessageDigest.getInstance("SHA-512");
  
            // digest() method is called
            // to calculate message digest of the input string
            // returned as array of byte
            byte[] messageDigest = md.digest(input.getBytes());
  
            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);
  
            // Convert message digest into hex value
            String hashtext = no.toString(16);
  
            // Add preceding 0s to make it 32 bit
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
  
            // return the HashText
            return hashtext;
        }
  
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
   ``` 
передаем строку с входными данными, где хранятся конкатенация пароля и логина, для преобразований с помощью алгоритма.
   Инициализируются в статическом методе getInstance() . После выбора алгоритма вычисляется значение дайджеста сообщения (так называют выходное сообщение), и результаты возвращаются в виде массива байтов. Класс BigInteger используется для преобразования результирующего массива байтов в его знаковое представление. Затем это представление преобразуется в шестнадцатеричный формат для получения ожидаемого MessageDig
   
   Для сообщения GeeksForGeeks получим хеш
```
acc10c4e0b38617f59e88e49215e2e894afaee5ec948c2af6f44039f03c9fe47a9210e01d5cd926c142bdc9179c2ad30f927a8faf69421ff60a5eaddcf8cb9c
 ```
 4. про расшифровку
SHA-512 — это [криптографическая хэш-функция](http://en.wikipedia.org/wiki/Cryptographic_hash_function) . Криптографические хэш-функции — это один из способов : вы можете вычислить хеш для блока данных, но невозможно вернуть исходные данные, когда у вас есть только хэш. Таким образом, вы не можете расшифровать хэш-код, чтобы вернуть исходные данные.

Криптографические хеш-функции часто используются для хранения паролей в базе данных. Чтобы проверить правильность введенного пользователем пароля, первое, что вы можете подумать: «Хорошо, значит, я должен расшифровать пароль в базе данных и проверить, совпадает ли он с тем, что ввел пользователь». Это, однако, не то, как вы это делаете.

Вместо этого вы хэшируете пароль, введенный пользователем, и сравниваете этот хэш с хешем, хранящимся в базе данных. Если хэши совпадают, пользователь ввел правильный пароль. Вам не нужно «расшифровывать» хэш.

**Comment by Denishka** [comment]
Implemented in "schedule" branch
