### ISSUE TITLE
DB deploy on new machines

### ISSUE THREAD

**Issue by software-engineering-labs6412** [software-engineering-labs6412/private-channel#11]
Разобраться, как развертывать базы данных на новых машинах (в докере) и организовать "one click deployment".

Создать инструмент, который поможет устанавливать бд инстанс на машину.

Подготовить параграф в installation notes для помощи пользователям в развёртке docker контейнера с postgres-инстансом.

**Comment by SobolevD** [comment]
Ready in installation-notes branch. Merged to master
