### ISSUE TITLE
[Client + Server] Scheduler implementation

### ISSUE THREAD

**Issue by SobolevD** [software-engineering-labs6412/private-channel#3]
1) Необходимо разобраться, что проще и лучше: QuartzScheduler или встроенный Spring Scheduler (аннотация @Scheduler);
2) Разобраться, как настраивать скедулер на определенные моменты времени (в каком формате передавать время). **CRON мы не рассматриваем**;
3) Сделать скедулер, который на вход будет принимать что-то типа потока. В момент назначения он будет этот поток запускать;
4) Предоставить API для создания таски для скедулера и для ее удаления.

**Comment by Denishka** [comment]
Коммент из хабра
****
По своему опыту могу сказать что кварц — штука крайне неудобная, с запутанным API и создаёт кучу непонятных таблиц, которых сложно контролировать.
Как уже выше писали @EnableScheduling работает превосходно. Лок на уровне базы, если надо, делается элементарно. Если требуется динамическое обновление, то это делается в один класс.
В конце концов, можно периодически запускать проверку и через CronSequenceGenerator узнавать нужно ли что либо выполнять в данный момент.
****

**Comment by SobolevD** [comment]
Пожалуйста, обрати внимание на это:
https://stackoverflow.com/questions/46974272/how-to-add-new-schedule-job-dynamically-with-spring

**Comment by SobolevD** [comment]
Может быть полезно:
https://technicalsand.com/spring-task-scheduler-examples/

Нам нужно скедулить таски динамически. Поэтому, могут помочь следующие параграфы:
**Schedule a task with Spring programmatically**
**Dynamically Schedule Spring tasks to run later**

**Comment by Denishka** [comment]
Implemented in "schedule" branch
